name: Netlify Deploy

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Site
        run: npm run build

      - name: Publish to Netlify
        uses: South-Paw/action-netlify-cli@v2
        id: netlify
        with:
          # We deploy the 'build' folder which contains the compiled React app
          args: 'deploy --dir "./build" --message "Deploy from GitHub Actions [${{ github.sha }}]"'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
